### ISSUE TITLE
Build Flavor Page

### ISSUE THREAD

**Issue by annazelenka** [khalludi/ice-cream-app#2]
### What
Represents an ice cream flavor and reviews for that flavor.
- [x] Flavor name
- [x] Flavor photo
- [x] Average rating
- [x] Description
- [x] Reviews (review title, username, star rating, date last edited, review content)
- [x] Floating Action Button to add review or edit review if user has already added review
- [x] Dialog to add review that adds review to top of ListView of reviews
- [x] Dialog to edit preexisting review

### Why
This flavor page front-end represents the front-end for user interaction with our tables of reviews for each ice cream brand as well as for the table of ice cream flavors. This user interaction consists of CRUD operations: create review, read review, update review, and add review.

### How
We will use Flutter, especially Material Components.
