### ISSUE TITLE
Build CRUD for Review Entities

### ISSUE THREAD

**Issue by khalludi** [khalludi/ice-cream-app#5]
### WHAT

Allow the frontend to perform CRUD operations on the review tables for Breyers.

### WHY

The application needs to perform CRUD operations on reviews in the Ice Cream Dataset.

### HOW

- [x] Write OpenAPI Spec #8 
- [x] Create an API Gateway Layer
- [ ] Write a Google Cloud Function for Create
- [x] Write a Google Cloud Function for Retrieve
- [ ] Write a Google Cloud Function for Update
- [ ] Write a Google Cloud Function for Delete

**Comment by khalludi** [comment]
Priorities changed. Anna is now responsible for Reviews functionality.
